version: 2

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOPRIVATE=github.com/turbot
    goos:
      - linux
      - darwin

    goarch:
      - amd64
      - arm64

    id: "steampipe"
    binary: "{{ .ProjectName }}.plugin"

archives:
  - formats: [gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
